# Generated by Django 4.0.4 on 2022-05-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0002_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
