# Generated by Django 4.0.4 on 2022-05-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0003_imagecategory_imagelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artgallery.imagecategory'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artgallery.imagelocation'),
        ),
    ]
