# Generated by Django 4.0.4 on 2022-05-30 08:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0004_images_image_category_images_image_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['image_location']},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
